/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BDropdown: typeof import('bootstrap-vue-next')['BDropdown']
    BDropdownDivider: typeof import('bootstrap-vue-next')['BDropdownDivider']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BForm: typeof import('bootstrap-vue-next')['BForm']
    BFormCheckbox: typeof import('bootstrap-vue-next')['BFormCheckbox']
    BFormCheckboxGroup: typeof import('bootstrap-vue-next')['BFormCheckboxGroup']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next')['BFormSelect']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BOverlay: typeof import('bootstrap-vue-next')['BOverlay']
    BPopover: typeof import('bootstrap-vue-next')['BPopover']
    BToast: typeof import('bootstrap-vue-next')['BToast']
    Clasificado: typeof import('./src/components/Clasificado.vue')['default']
    Gallery: typeof import('./src/components/Gallery.vue')['default']
    GoogleMapLoader: typeof import('./src/components/GoogleMapLoader.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LineScale: typeof import('./src/components/utils/loader/loaders/line-scale.vue')['default']
    Loader: typeof import('./src/components/utils/loader/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tipos: typeof import('./src/components/Tipos.vue')['default']
    TiposEdit: typeof import('./src/components/TiposEdit.vue')['default']
    Uploader: typeof import('./src/components/utils/Uploader.vue')['default']
  }
}
